Repository Bitcoin-com/badger-mobile, pull requests merged in 2019-07, with the labels that each got.

#117 uri-scheme PR
  .prettierrc
  App.js
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/badgerMobile/AppDelegate.m
  ios/badgerMobile/Info.plist
  navigation/AppNavigator.js
  navigation/AuthLoadingScreen.js
  screens/SendSetupScreen.js
  utils/account-utils.js
  utils/schemeParser-utils.js
Labels: enhancement

#119 Bugs - minor bugs for URI PR
  atoms/Button/Button.js
  navigation/AuthLoadingScreen.js
  screens/SendConfirmScreen.js
  screens/SendSetupScreen.js
  screens/SendSuccessScreen.js
  screens/WalletDetailScreen.js
Labels: bug

#124 Only prefill URI's with single amounts
  CHANGELOG.md
  navigation/AuthLoadingScreen.js
  screens/RequestScreen.js
  screens/SendSetupScreen.js
Labels: enhancement

#126 0.9.0 - Open from URI's
  .flowconfig
  .prettierrc
  App.js
  CHANGELOG.md
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/ic_launcher-web.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  assets/images/icon-1024.png
  assets/images/token-icons/1074bafb678b85f90bca79fa201a26011e09bfc6f723b95c770c0850f8d44fe8.png
  assets/images/token-icons/527a337f34e04b1974cb8a1edc7ca30b2e444bea111afc122259552243c1dbe3.png
  assets/images/token-icons/56ff58fd263736172f0b707c014ea8272d633cc0986b2ffb70e7e209bcc4adad.png
  assets/images/token-icons/959a6818cba5af8aba391d3f7649f5f6a5ceb6cdcd2c2a3dcb5d2fbfc4b08e98.png
  assets/images/token-icons/c4b0d62156b3fa5c8f3436079b5394f7edc1bef5dc1cd2f9d0c4d46f82cca479.png
  atoms/Button/Button.js
  ios/Podfile.lock
  ios/badgerMobile/AppDelegate.m
  ios/badgerMobile/Images.xcassets/AppIcon.appiconset/Icon.png
  ios/badgerMobile/Images.xcassets/AppIcon.appiconset/icon_20pt@2x.png
  ios/badgerMobile/Images.xcassets/AppIcon.appiconset/icon_20pt@3x.png
  ios/badgerMobile/Images.xcassets/AppIcon.appiconset/icon_29pt@2x.png
  ios/badgerMobile/Images.xcassets/AppIcon.appiconset/icon_29pt@3x.png
  ios/badgerMobile/Images.xcassets/AppIcon.appiconset/icon_40pt@2x.png
  ios/badgerMobile/Images.xcassets/AppIcon.appiconset/icon_40pt@3x.png
  ios/badgerMobile/Images.xcassets/AppIcon.appiconset/icon_60pt@2x.png
  ios/badgerMobile/Images.xcassets/AppIcon.appiconset/icon_60pt@3x.png
  ios/badgerMobile/Info.plist
  navigation/AppNavigator.js
  navigation/AuthLoadingScreen.js
  navigation/MainTabNavigator.js
  package.json
  screens/RequestScreen.js
  screens/SendConfirmScreen.js
  screens/SendSetupScreen.js
  screens/SendSuccessScreen.js
  screens/WalletDetailScreen.js
  utils/account-utils.js
  utils/balance-utils.js
  utils/schemeParser-utils.js
  utils/token-utils.js
Labels: release

#127 Hotfix - Fixing launch crash on android
  android/app/build.gradle
  ios/badgerMobile/Info.plist
  navigation/AuthLoadingScreen.js
  package.json
  screens/SendSetupScreen.js
Labels: bug

#128 Hotfix - Fixing launch crash on android (#127)
  android/app/build.gradle
  ios/badgerMobile/Info.plist
  navigation/AuthLoadingScreen.js
  package.json
  screens/SendSetupScreen.js
Labels: bug

#130 Bug - Make unknown SLP types unspendable
  data/utxos/actions.js
Labels: bug

#132 Updates - packages build improvements
  README.md
  package.json
  utils/transaction-utils.js
  yarn.lock
Labels: enhancement
